import mongoose from 'mongoose';
import { TErrorSources, TGenericErrorResponse } from '../interfaces/error';

const handleCastError = (
  err: mongoose.Error.CastError,
): TGenericErrorResponse => {
  // Creating error source for CastError
  const errorSources: TErrorSources = [
    {
      path: err.path, // Path where the cast error occurred
      message: err.message, // The error message generated by Mongoose
    },
  ];

  const statusCode = 400;

  return {
    success: false, // Indicating failure in case of invalid ID
    statusCode,
    message: 'Invalid ID', // Custom message for invalid ID error
    error: {
      details: errorSources, // Providing error details
    },
    stack: err.stack, // Optionally, include the stack trace for debugging
  };
};

export default handleCastError;
